import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import reactHooks from 'eslint-plugin-react-hooks';
import globals from 'globals';

export default tseslint.config(
    {
        // wailsjs is generated by the Wails toolchain and gitignored; dist is
        // build output. Linting either produces noise nobody can act on.
        ignores: ['dist/**', 'wailsjs/**', 'node_modules/**'],
    },

    js.configs.recommended,
    ...tseslint.configs.recommended,

    {
        files: ['**/*.{ts,tsx}'],
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType: 'module',
            globals: { ...globals.browser, ...globals.es2021 },
        },
        plugins: { 'react-hooks': reactHooks },
        rules: {
            ...reactHooks.configs.recommended.rules,

            // Warn, not error, on the two rules the codebase knowingly bends.
            //
            // exhaustive-deps: several polling effects deliberately omit deps to
            // avoid re-subscribing on every tick (see the eslint-disable
            // comments in node/main.tsx and resourcequota/main.tsx — until this
            // config existed those directives were inert).
            //
            // no-explicit-any: ~90 escapes concentrated in the PrimeReact and
            // dockview seams, where the library types are themselves loose.
            // Both should trend to zero; neither should block a build today.
            'react-hooks/exhaustive-deps': 'warn',
            '@typescript-eslint/no-explicit-any': 'warn',
            '@typescript-eslint/no-unused-vars': [
                'warn',
                { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
            ],
        },
    },

    {
        // Node-side config files run outside the browser.
        files: ['*.config.{js,ts}', 'scripts/**/*.{js,mjs}'],
        languageOptions: { globals: globals.node },
    },
);
