VERSION := $(shell git describe --tags --abbrev=0 | sed 's/^v//')
LDFLAGS := -X 'kube-ins/internal/business.appVersion=$(VERSION)' -s -w

# The Trivy library (security scanner) depends on encoding/json/v2, which is
# gated behind the jsonv2 GOEXPERIMENT on Go 1.26. Export it so every wails/go
# invocation in this Makefile (build, dev, packaging) compiles it.
export GOEXPERIMENT := jsonv2
export GOFLAGS := -trimpath -buildvcs=false
NFPM    := nfpm
DIST    := ./dist

# Optional Wails build tags. On distros that ship webkit2gtk-4.1 instead of
# 4.0 (Ubuntu 24.04+, Fedora 40+), build with: make build-linux WAILS_TAGS=webkit2_41
TAGS    := $(if $(WAILS_TAGS),-tags "$(WAILS_TAGS)",)

# ── Wails shell: development only ───────────────────────────────────────────
# The shipped GUI is the Electron shell (see the pkg-* targets). These stay for
# developing and debugging against the system webview; they produce no release
# artifact and nothing here is used by CI.
build:
	wails build $(TAGS) -ldflags "$(LDFLAGS)"

build-linux:
	wails build $(TAGS) -platform linux/amd64 -ldflags "$(LDFLAGS)"

build-windows:
	wails build -platform windows/amd64 -nsis -ldflags "$(LDFLAGS)"

build-mac:
	wails build -platform darwin/universal -ldflags "$(LDFLAGS)"

dev:
	wails dev -ldflags "-X 'kube-ins/internal/business.appVersion=$(VERSION)-dev'"

# Hızlı TUI geliştirme: webview-free CLI'yi doğrudan çalıştırır. Vite tarzı hot
# reload yoktur (TUI terminali tam ekran ele geçirir); döngü: düzenle → q ile çık
# → tekrar `make dev-tui`. Go build cache sayesinde ilk derlemeden sonra hızlıdır.
dev-tui:
	go run $(GOFLAGS) -tags tui -ldflags "-X 'kube-ins/internal/business.appVersion=$(VERSION)-dev'" ./cmd/tui

# ── Standalone terminal UI (kube-inspector-cli) ──────────────────
# A webview-free native CLI binary (cmd/tui). Plain `go build` — no wails, no
# frontend embed — so it carries no webkit2gtk dependency. GOEXPERIMENT=jsonv2
# is still required because internal/business transitively imports Trivy.
build-tui:
	go build $(GOFLAGS) -tags tui -ldflags "$(LDFLAGS)" -o build/bin/kube-inspector-cli ./cmd/tui

build-tui-linux:
	GOOS=linux GOARCH=amd64 go build $(GOFLAGS) -tags tui -ldflags "$(LDFLAGS)" -o build/bin/kube-inspector-cli ./cmd/tui

build-tui-windows:
	GOOS=windows GOARCH=amd64 go build $(GOFLAGS) -tags tui -ldflags "$(LDFLAGS)" -o build/bin/kube-inspector-cli.exe ./cmd/tui

# Universal macOS CLI binary (Apple Silicon + Intel). Uses lipo, so this target
# only runs on macOS (same constraint as build-mac).
build-tui-mac:
	GOOS=darwin GOARCH=amd64 go build $(GOFLAGS) -tags tui -ldflags "$(LDFLAGS)" -o build/bin/kube-inspector-cli-amd64 ./cmd/tui
	GOOS=darwin GOARCH=arm64 go build $(GOFLAGS) -tags tui -ldflags "$(LDFLAGS)" -o build/bin/kube-inspector-cli-arm64 ./cmd/tui
	lipo -create -output build/bin/kube-inspector-cli build/bin/kube-inspector-cli-amd64 build/bin/kube-inspector-cli-arm64
	rm -f build/bin/kube-inspector-cli-amd64 build/bin/kube-inspector-cli-arm64

# ── Shipped GUI: the Electron shell ─────────────────────────────────────────
# Electron embeds its own Chromium, so the packages carry no libwebkit2gtk
# dependency and one build works on every distro. The Wails shell is
# development-only (see `dev` / `build` above) and is no longer packaged.
#
# Division of labour: electron-builder *builds* into build/electron, nfpm
# *packages* into dist/. dist/ holds shippable artifacts only — CI syncs the
# whole directory to the public bucket. See build/nfpm.yaml for why deb/rpm are
# not left to electron-builder.

# Sidecar: plain `go build`, no wails, no webview linkage. The Go binary is the
# application; Electron only supplies the window.
build-sidecar:
	go build -ldflags "$(LDFLAGS)" -o build/bin/kube-inspector ./

# `npm ci` rather than `npm install`: it installs exactly what the lockfiles
# pin, so a release build can never silently pick up a newer transitive version.
# Everything that builds the frontend depends on this — without it a fresh CI
# checkout has no node_modules and `npm run build` falls through to whatever
# stray global `tsc` the runner happens to have (or none at all).
deps:
	cd frontend && npm ci
	cd electron && npm ci

# frontend/wailsjs is gitignored and generated by the Wails toolchain, and
# `npm run build` runs tsc against it — so packaging still needs the wails CLI
# present. The alternative is committing generated bindings, which this project
# deliberately avoids.
#
# The mkdir/touch is not cosmetic: `wails generate module` parses main.go, whose
# //go:embed all:frontend/dist needs at least one file to exist — but that
# directory is only created by the npm build below, which in turn needs the
# bindings. Vite empties the directory, so the placeholder is restored after.
electron-frontend: deps
	mkdir -p frontend/dist && touch frontend/dist/.gitkeep
	wails generate module
	cd frontend && npm run build
	touch frontend/dist/.gitkeep

electron-app: electron-frontend build-sidecar
	cd electron && npx electron-builder --linux --publish never -c.extraMetadata.version=$(VERSION)

pkg-deb: electron-app
	mkdir -p $(DIST)
	VERSION=$(VERSION) $(NFPM) pkg --packager deb --config ./build/nfpm.yaml --target $(DIST)/

pkg-rpm: electron-app
	mkdir -p $(DIST)
	VERSION=$(VERSION) $(NFPM) pkg --packager rpm --config ./build/nfpm.yaml --target $(DIST)/

pkg-linux: pkg-deb pkg-rpm

pkg-windows: electron-frontend
	GOOS=windows GOARCH=amd64 go build -ldflags "$(LDFLAGS)" -o build/bin/kube-inspector.exe ./
	cd electron && npx electron-builder --win --publish never -c.extraMetadata.version=$(VERSION)
	mkdir -p $(DIST)
	cp build/electron/*.exe $(DIST)/

pkg-mac: electron-frontend
	GOOS=darwin GOARCH=arm64 go build -ldflags "$(LDFLAGS)" -o build/bin/kube-inspector ./
	cd electron && npx electron-builder --mac --publish never -c.extraMetadata.version=$(VERSION)
	mkdir -p $(DIST)
	cp build/electron/*.dmg $(DIST)/

# ── Standalone terminal UI (separate product) ───────────────────────────────

pkg-tui-deb: build-tui-linux
	mkdir -p $(DIST)
	VERSION=$(VERSION) $(NFPM) pkg --packager deb --config ./build/nfpm-cli.yaml --target $(DIST)/

pkg-tui-rpm: build-tui-linux
	mkdir -p $(DIST)
	VERSION=$(VERSION) $(NFPM) pkg --packager rpm --config ./build/nfpm-cli.yaml --target $(DIST)/

pkg-all: pkg-linux pkg-windows pkg-mac pkg-tui-deb pkg-tui-rpm

# ── Electron dev loop (three terminals) ─────────────────────────────────────
# Only `electron-dev-go` passes the kubeinsdev tag, which relaxes the token
# check and pins the port — it appears in no build-* or pkg-* target, so it
# cannot reach a release binary.
electron-dev-go:
	go run -tags kubeinsdev -ldflags "-X 'kube-ins/internal/business.appVersion=$(VERSION)-dev'" . --serve --shell-channel
electron-dev-vite:
	cd frontend && npm run dev
# env -u ELECTRON_RUN_AS_NODE: VS Code's integrated terminal exports it, which
# makes Electron boot as plain Node and every electron API come back undefined.
electron-dev:
	cd electron && env -u ELECTRON_RUN_AS_NODE KUBE_INS_DEV_URL=http://localhost:5173 npm start

clean:
	rm -rf ./build/bin ./build/electron ./dist

test-e2e:
	@echo "⚠  Make sure 'make dev' is running in another terminal (http://localhost:34115)."
	cd e2e_tests && pip install -q -r requirements.txt && \
		pytest -v --html=../report.html --self-contained-html

# ── Documentation (MkDocs Material) ──────────────────────────────
# Requires mkdocs-material on PATH: pip install mkdocs-material

# docs/downloads.md is tracked with a __VERSION__ placeholder; substitute the
# current git tag ($(VERSION)) in place before building/serving. In CI this runs
# on a fresh checkout. Locally, `git checkout docs/downloads.md` restores the
# placeholder if you need to rebuild for a different version.
docs-downloads:
	@echo "Substituting version v$(VERSION) into docs/downloads.md"
	@sed -i 's/__VERSION__/$(VERSION)/g' docs/downloads.md
	@echo "Writing docs/version.json for v$(VERSION) (in-app update check)"
	@printf '{"version":"%s","downloadUrl":"https://kubeinspector.com/downloads/"}\n' "$(VERSION)" > docs/version.json

docs-serve: docs-downloads
	mkdocs serve

docs-build: docs-downloads
	mkdocs build --clean --strict

.PHONY: build build-linux build-windows build-mac dev dev-tui build-tui build-tui-linux build-tui-windows build-tui-mac deps build-sidecar electron-frontend electron-app electron-dev-go electron-dev-vite electron-dev pkg-deb pkg-rpm pkg-linux pkg-windows pkg-mac pkg-tui-deb pkg-tui-rpm pkg-all clean test-e2e docs-downloads docs-serve docs-build
