// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function DeletePod(arg1:string,arg2:string):Promise<void>;

export function GetPods():Promise<Array<models.PodInfo>>;
