// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeletePod(arg1, arg2) {
  return window['go']['controller_app']['App']['DeletePod'](arg1, arg2);
}

export function GetPods() {
  return window['go']['controller_app']['App']['GetPods']();
}
